Poll/Models/ErrorViewModel.cs
using System;

namespace Poll.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Poll/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Poll.Models;
using Poll.Services;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Poll.Services.ViewModel;
using Microsoft.AspNetCore.Authorization;

namespace Poll.Controllers
{
    public class HomeController : Controller
    {
        
        private readonly IUsersService _usersService;

        public HomeController(IUsersService users)
        {
            _usersService = users;
        }

        [HttpGet]
        public IActionResult Index()
        {
            if (User.Identity.IsAuthenticated)
            {
                var userConnected = _usersService.GetUserWithClaims();
                ViewData["Claims"] = userConnected.Pseudo;
            }

            return View();
        }

        [HttpGet]
        public IActionResult Register()
        {
            if (!User.Identity.IsAuthenticated)
            {
                return View();
            }else{
                return Redirect("index");
            }
        }
        [HttpPost]
        public async Task<IActionResult> Register(RegisterViewModel model)
        {
            var resultRegistration = await _usersService.RegisterAsync(model);
            if(resultRegistration)
            {
                return Redirect("Login");
            }else{
                ModelState.AddModelError("model", "Le pseudo ou l'email est déjà utilisé");
                return View();
            }
            
        }
        [HttpGet]
        public IActionResult Login()
        {
            if (!User.Identity.IsAuthenticated)
            {
                return View();
            }else{
                return Redirect("/");
            }
            
        }

        [HttpPost]
        public async Task<IActionResult> Login(LoginViewModel model)
        {
            
            if (await _usersService.AuthenticatedAsync(model))
            {
                return Redirect("/");
            }else
            {
                ModelState.AddModelError("model", "L'email ou le mot de passe ne correspondent pas");
                return View();
            }

        }

        [HttpGet]
        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }

        [HttpGet]
        [Authorize]
        public async Task<IActionResult> Logout()
        {
            await _usersService.LogoutAsync();
            return LocalRedirect("/home/index");
        }
    }
}

Poll/Controllers/SurveyController.cs
using System;
using System.Linq;
using System.Diagnostics;
using System.Threading.Tasks;
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Poll.Services;
using Poll.Services.ViewModel;
using Microsoft.AspNetCore.Authorization;
using Poll.Data.Model;

namespace Poll.Controllers
{
    public class SurveyController : Controller
    {
        private readonly ILogger<SurveyController> _logger;
        private readonly ISurveyService _surveyService;
        private readonly IVoteService _voteService;

        public SurveyController(ILogger<SurveyController> logger, ISurveyService surveyService, IVoteService voteService)
        {
            _logger = logger;
            _surveyService = surveyService;
            _voteService = voteService;
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            IEnumerable<SurveyViewModel> model = await this._surveyService.GetListAsync();

            return View(model);
        }

        [HttpGet]
        [Authorize]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [Authorize]
        public async Task<IActionResult> Create(AddSurveyViewModel model)
        {
            if(!ModelState.IsValid)
                return View(model);
            
            try
            {
                string linkGuid = await this._surveyService.AddSurveyAsync(model);
                return Redirect($"/Survey/Links/{linkGuid}");
            }
            catch(NotEnoughChoicesException e)
            {
                ModelState.AddModelError("Choices", e.Message);
                return View(model);
            }
            catch(Exception e) when (
                e is ArgumentException ||
                e is ArgumentNullException
            )
            {
                ModelState.AddModelError("All", e.Message);
                return View(model);
            }

        }

        [HttpGet]
        [Authorize]
        public async Task<IActionResult> Links([FromRoute] string guid)
        {
            LinkViewModel model = await this._surveyService.GetLinkViewModelAsync(guid);
            
            return View(model);
        }
        
        [HttpPost]
        [Authorize]
        public async Task<IActionResult> Invite(LinkViewModel model)
        {
            await this._surveyService.SendEmailInvitationAsync(model);

            return Redirect("/Survey");
        }

        [HttpGet]
        [Authorize]
        public async Task<IActionResult> Vote([FromRoute] string guid)
        {
            VoteViewModel model;
            try
            {
                model = await this._voteService.GetVoteViewModelAsync(guid);
            }
            catch(SurveyDeactivatedException)
            {
                string resultGuid = await this._surveyService.GetResultGuidFromVoteGuidAsync(guid);
                return Redirect($"/Survey/Result/{resultGuid}");
            }
            catch(Exception e) when (
                e is ArgumentException ||
                e is ArgumentNullException
            )
            {
                _logger.LogError("Did throw", e);
                return Redirect("/Survey");
            }

            return View(model);
        }

        
        [HttpPost]
        [Authorize]
        public async Task<IActionResult> Vote([FromRoute] string guid, VoteViewModel a)
        {
            await this._voteService.AddVoteAsync(guid, a);

            return Redirect("/Survey");
        }

        [HttpGet]
        [Authorize]
        public async Task<IActionResult> Deactivate([FromRoute] string guid)
        {
            await this._surveyService.DeactivateAsync(guid);

            return Redirect("/Survey");
        }
        
        [HttpGet]
        [Authorize]
        public async Task<IActionResult> Delete([FromRoute] string guid)
        {
            await this._surveyService.DeleteAsync(guid);

            return Redirect("/Survey");
        }

        [HttpGet]
        public async Task<IActionResult> Result([FromRoute] string guid)
        { 
            Survey survey = await _surveyService.GetSurveyAsync(guid);
            if (survey == null) { return Redirect("/Survey"); }

            ViewData["Name"] = survey.Name ;
            ViewData["Description"] = survey.Description;
            ViewData["Vote"] = _surveyService.GetNumberVote(survey.Id);

            var data = await _surveyService.GetResultAsync(survey.Id);
            if (data == null) { return View("Error"); }

            return View(data);
        }
    }
}

Poll/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Bienvenue @ViewData["Claims"] !</h1>
    @if(@ViewData["Claims"] != null)
    {
        <p>Cliquez <a href="/Survey">ici</a> pour voir la liste des sondages.</p>
    }else{
        <p>Pour voter vous devez être connecter.</p>
    }
    <img class="img-responsive" src="~/img/lappy.gif" alt="funny GIF" style="height: calc(1.5em + .75rem + 340px)";>
</div>

Poll/Views/Home/Login.cshtml
@model Poll.Services.ViewModel.LoginViewModel

@{
    ViewData["Title"] = "Login";
}

<h1>Connexion</h1>


<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Login">
            <div asp-validation-summary="All" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Password" class="control-label">Mot de passe</label>
                <input asp-for="Password" class="form-control" />
                <span asp-validation-for="Password" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Me connecter" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Retour vers la page d'accueil</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Poll/Views/Home/Register.cshtml
@model Poll.Services.ViewModel.RegisterViewModel

@{
    ViewData["Title"] = "Register";
}

<h1>Register</h1>


<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Register">
            <div asp-validation-summary="All" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Pseudo" class="control-label"></label>
                <input asp-for="Pseudo" class="form-control" />
                <span asp-validation-for="Pseudo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Password" class="control-label">Mot de passe</label>
                <input asp-for="Password" class="form-control" />
                <span asp-validation-for="Password" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="RepeatPassword" class="control-label">Répétez le mot de passe</label>
                <input asp-for="RepeatPassword" class="form-control" />
                <span asp-validation-for="RepeatPassword" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="S'inscrire" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Retour vers la page d'accueil</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Poll/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Poll</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body style="background-color: #EFEFEF;">
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm bg-primary text-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand text-white" asp-area="" asp-controller="Home" asp-action="Index"><img height="35px" src="/img/poll.png" alt="Poll"/></a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Home" asp-action="Index">Accueil</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Survey" asp-action="Index">Liste des sondages</a>
                        </li>
                        @if (User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-white" asp-area="" asp-controller="Survey" asp-action="Create">Créer un sondage</a>
                            </li>
                        }
                        
                    </ul>
                </div>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-end ">
                    <ul class="navbar-nav">

                        @if (!User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-white" asp-area="" asp-controller="Home" asp-action="Login">Se connecter</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-white" asp-area="" asp-controller="Home" asp-action="Register">S'inscrire</a>
                            </li>
                        }else{
                            <li class="nav-item">
                                <a class="nav-link text-white" asp-area="" asp-controller="Home" asp-action="Logout">Se déconnecter</a>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - Poll - <a asp-area="" asp-controller="Home" asp-action="Privacy">Condition général</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Poll/Views/Survey/Create.cshtml
@model Poll.Services.ViewModel.AddSurveyViewModel

@{
    ViewData["Title"] = "Créer un sondage";
}

<h1>@ViewData["Title"]</h1>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create" method="post">
            <div asp-validation-summary="All" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="IsMultipleChoices" class="control-label"></label>
                <input asp-for="IsMultipleChoices" class="form-control" />
                <span asp-validation-for="IsMultipleChoices" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="IsPrivate" class="control-label"></label>
                <input asp-for="IsPrivate" class="form-control" />
                <span asp-validation-for="IsPrivate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DeactivateDate" class="control-label"></label>
                <input asp-for="DeactivateDate" class="form-control" />
                <span asp-validation-for="DeactivateDate" class="text-danger"></span>
            </div>
            <span asp-validation-for="Choices" class="text-danger"></span>
            <div id="choice-container">
                <div class="form-group" id="choice1">
                    <label class="control-label"> Choix 1</label>
                    <input asp-for="Choices[0]" class="form-control" maxlength="50" />
                </div>
                <div class="form-group" id="choice2">
                    <label class="control-label"> Choix 2</label>
                    <input asp-for="Choices[1]" class="form-control" />
                    <span asp-validation-for="Choices[1]" class="text-danger" maxlength="50"></span>
                </div>
            </div>
            <div class="mb-4 pointer">
                <a class="link" onclick="addChoice()" > + Ajouter un choix</a>
            </div>
            <div class="form-group">
                <input type="submit" value="Créer le sondage" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

@section Scripts {
     <script type="text/javascript" src="/js/Survey/Create.js"></script>
}

Poll/Views/Survey/Index.cshtml
@using Poll.Services.ViewModel;
@model IEnumerable<SurveyViewModel>;

@{
    ViewData["Title"] = "Sondage";
}

<h1>@ViewData["Title"]</h1>

<div class="container d-flex justify-content-end">

<button class="btn btn-primary " onclick="window.location.href = '/Survey/Create'">Créer un sondage</button>
</div>

<div class="container mt-5">
    <div class="row my-2 font-weight-bold text-center">
        <span class="col">Nom</span>
        <span class="col">Créateur</span>
        <span class="col">Statut <br> Date désactivation</span>
        <span class="col">Date de création</span>
        <span class="col">Actions</span>
    </div>
    @foreach(SurveyViewModel survey in Model)
    {
        <div class="card my-2">
            <div class="row py-2 text-center">
                @if(survey.IsCurrentUser)
                {
                    <div class="user-indicator bg-blue"></div>
                }
                else 
                {
                    <div class="user-indicator"></div>
                }
                <span class="col pl-0 font-weight-bold">@survey.PollName</span>
                <span class="col">@survey.Username</span>
                <div class="col">
                    @if(survey.IsActive)
                    {
                        <span>Ouvert</span>
                    }
                    else 
                    {
                        <span>Fermé</span>
                    }
                    <br>
                    @if(String.IsNullOrEmpty(survey.DeactivateDate))
                    {
                        <span>Pas de date d'expiration</span>
                    }
                    else 
                    {
                        <span>@survey.DeactivateDate</span>
                    }
                </div>
                <span class="col">@survey.CreationDate</span>
                <div class="col">
                    @if (User.Identity.IsAuthenticated)
                    {
                        @if (survey.IsActive)
                        {
                            <div class="pointer py-1"> 
                                @if (survey.UserDidVote)
                                {
                                    <a class="link" href="/Survey/Vote/@survey.GuidVote">Modifier mon vote</a>
                                }
                                else
                                {
                                    <a class="link" href="/Survey/Vote/@survey.GuidVote">Voter</a>
                                }
                            </div>
                            if (survey.IsCurrentUser)
                            {
                                <div class="pointer py-1"> <a class="link" href="/Survey/Deactivate/@survey.GuidDeactivate">Désactiver le sondage</a> </div>
                            }
                            <div class="pointer py-1"> <a class="link" href="/Survey/Result/@survey.GuidResult">Voir les résultats</a> </div>
                        }
                        else
                        {
                            <div class="pointer py-1"> <a class="link" href="/Survey/Result/@survey.GuidResult">Voir les résultats</a> </div>
                        }
                        @if(survey.IsCurrentUser)
                        {
                            <div class="pointer py-1"> <a class="link" href="/Survey/Delete/@survey.GuidDeactivate">Supprimer le sondage</a> </div>
                        }
                    }
                    else
                    {
                        <div class="pointer py-1"> <a class="link" href="/Survey/Result/@survey.GuidResult">Voir les résultats</a> </div>
                    }
                </div>
            </div>
        </div>
    }
</div>

Poll/Views/Survey/Links.cshtml
@using Poll.Services.ViewModel;
@model LinkViewModel;

@{
    ViewData["Title"] = "Liste des sondages";
}

<h1>@ViewData["Title"]</h1>

<div>
    <h4> Vous venez de créer le sondage <strong>@Model.Name</strong></h4>
    <p>Vous pouvez retrouver les liens importants du sondage ci dessous</p>
</div>

<div class="container mt-5">
    <p><strong>Lien de vote </strong> : <a id="vote"> </a></p>
    <p><strong>Lien de désactivation </strong> : <a id="deactivate"> </a></p>
    <p><strong>Lien de résultat </strong> : <a id="result"> </a></p>

</div>

<div class="row mt-5">
    <div class="col-md-4">
        <h4>Invitez vos amis ou collègues !</h4>
        <p>Rentrez leur adresse email, on s'occupe de tout.</p>
        <form asp-action="Invite" method="post">
            <span asp-validation-for="Emails" class="text-danger"></span>
            <div id="email-container">
                <div class="form-group" id="choice1">
                    <input type="email" asp-for="Emails[0]" class="form-control" />
                </div>
            </div>
            <div class="mb-4 pointer">
                <a class="link" onclick="addChoice()" > + Ajouter un champ</a>
            </div>
            <div class="form-group">
                <input type="submit" value="Envoyer" class="btn btn-primary" />
            </div>
            <input type="hidden" asp-for="@Model.GuidLink" />
        </form>
    </div>
</div>

@section Scripts {
    <script>
        const voteElement =  document.getElementById('vote')
        voteElement.href = "../Vote/" + "@Model.GuidVote";
        voteElement.textContent = voteElement.href;

        const deactivateElement =  document.getElementById('deactivate')
        deactivateElement.href = "../Deactivate/" + "@Model.GuidDeactivate";
        deactivateElement.textContent = deactivateElement.href;

        const resultElement =  document.getElementById('result')
        resultElement.href = "../Result/" + "@Model.GuidResult";
        resultElement.textContent = resultElement.href;
    </script>

    <script type="text/javascript" src="/js/Survey/Link.js"></script>
}

Poll/Views/Survey/Result.cshtml
@model IEnumerable<Poll.Services.ViewModel.ResultViewModel>

@{
    ViewData["Title"] = "Result";
}
<script src="https://cdn.jsdelivr.net/npm/chart.js"></script>


<h1>Resultat du sondage</h1>

<p>
    <a asp-action="Index">Retour à la liste des sondages</a>
</p>
<h2>@ViewData["Name"]</h2>

<p>Nombre de votant : @ViewData["Vote"]</p>    
<hr />
<p>@ViewData["Description"]</p>

<script>
    let lab = [];
    let dat = [];
</script>
@foreach (var item in Model) {
    <script>
        lab.push("@item.NameChoice")
        dat.push("@item.vote")
    </script>
}

<div>
  <canvas id="myChart"></canvas>
</div>
<script>
  const labels = lab;

  const data = {
    labels: labels,
    datasets: [{
      label: 'Résultat du sondage',
      backgroundColor: 'rgb(0, 123, 255)',
      borderColor: 'rgb(20, 123, 255)',
      data: dat,
    }]
  };

     const config = {
      type: 'bar',
      data,
      options: {
        indexAxis: 'y',
      }
    };

  const myChart = new Chart(
    document.getElementById('myChart'),
    config
  );
</script>

Poll/Views/Survey/Vote.cshtml
@using Poll.Services.ViewModel;
@model VoteViewModel
@{
    ViewData["Title"] = "Voter";
}

<h1>@ViewData["Title"]</h1>
<h3>@Model.PollName</h3>
<h5>Nombre de votant : @Model.NumberOfVoter</h5>
@if(String.IsNullOrEmpty(Model.DeactivateDate))
{
    <h5>Pas de date d'expiration</h5>
}
else 
{
    <h5>Date d'expiration : @Model.DeactivateDate</h5>
}
<hr />
@if(!String.IsNullOrWhiteSpace(Model.Description))
{
    <p class="px-5">
        @Model.Description

    </p>
}
<div class="row">
    <div class="col-md-4">
        <form asp-action="Vote" asp method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div id="choice-container">
                @for (int i = 0; i < Model.Choices.Count(); i++)
                    {
                        <div class="form-group">
                            <input class="checkbox" type="checkbox" asp-for="@Model.Choices[i].Selected"/>
                            <label class="control-label"> @Model.Choices[i].Name </label>
                            <input type="hidden" asp-for="@Model.Choices[i].Id" />
                            <input type="hidden" asp-for="@Model.Choices[i].SelectedBefore" />
                        </div>
                    }
            </div>
            <div class="form-group">
                <input type="submit" value="Envoyer mon vote" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @if(!Model.IsMultipleChoice)
    {
        <script type="text/javascript" src="/js/Survey/VoteSingleChoice.js"></script>
    }
}